# Site Settings
title: Start Jekyll
email:
description: >
  Hello, I’m Shreya Boyapati, a computer science student with a passion for
  software engineering and cloud computing. I am urrently pursuing a Master’s degree
  at the University of Illinois at Urbana-Champaign.
baseurl: "/start"
url: "http://Shreya-Boyapati.github.io"
twitter_username:
github_username:  Shreya-Boyapati
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM